### ISSUE TITLE
Slow training or OOM Error on single gpu

### ISSUE THREAD

**Issue by jdubkim** [danijar/director#6]
Hi Danijar, thank you so much for helping me running the code.
It took some time to run different tasks, in order to provide more information.
So, I think there are two problems in the code at the moment.

1) For vision tasks, VRAM memory gets exhausted right after collecting pre-training samples, even on GPU with 16/24GB VRAM.
2) Even for tasks that do not require vision (such as dmc_proprio), training is about 20x slower than expected. To be more specific about this, I found out that "fps" value in the logger is between 2 to 5. I have checked other parts of the training code and measured time to see if there is any bottlenecks in the code, but I was not able to find one.

Here, I will attach the outputs of each task. (Each of them has a link to gist)
1. [dmc_vision / dmc_walker_walk](https://gist.github.com/jdubkim/63b6ddda09ab74757f21edba908909d8): RESOURCE_EXHAUSTED Error after collecting pre-train samples

2. [dmc_proprio / dmc_walker_walk](https://gist.github.com/jdubkim/6bef23c36e4588de71955b114e5bd479): In line 821, you can see that fps is 3.1. It took about 15 hours to collect 200k steps. (+ In line 809, train/duration is 3220.91, which means each train_step is taking approx. 50 minutes?)

3. [loconav / loconav_ant_maze_m](https://gist.github.com/jdubkim/0daa39845a544862092783c4edd3962a): RESOURCE_EXHAUSTED Error after collecting pre-train samples

I also tried changing number of envs to 1 or changing the batch size to 1, but it did not make a difference. It would be amazing if you could help me figure out what causes this problem. Thank you so much. 

---------------------------------------------------------------------------------------------------------
Below is the list of python packages I installed on my virtual env (python 3.10).
```
Package                            Version
---------------------------------- ---------
absl-py                            1.4.0
astunparse                         1.6.3
atari-py                           0.2.9
backports.shutil-get-terminal-size 1.0.0
bcrypt                             4.0.1
cachetools                         5.3.0
certifi                            2022.12.7
cffi                               1.15.1
charset-normalizer                 3.1.0
cloudpickle                        1.6.0
colorama                           0.4.6
contourpy                          1.0.7
crafter                            1.8.0
cryptography                       40.0.1
cycler                             0.11.0
decorator                          5.1.1
dm-control                         1.0.11
dm-env                             1.6
dm-sonnet                          2.0.1
dm-tree                            0.1.8
flatbuffers                        23.3.3
fonttools                          4.39.3
gast                               0.4.0
glfw                               2.5.9
google-auth                        2.17.1
google-auth-oauthlib               0.4.6
google-pasta                       0.2.0
grpcio                             1.53.0
gym                                0.19.0
gym-minigrid                       1.0.3
h5py                               3.8.0
idna                               3.4
imageio                            2.27.0
keras                              2.8.0
Keras-Preprocessing                1.1.2
kiwisolver                         1.4.4
labmaze                            1.0.6
libclang                           16.0.0
llvmlite                           0.39.1
lxml                               4.9.2
Markdown                           3.4.3
markdown-it-py                     2.2.0
MarkupSafe                         2.1.2
matplotlib                         3.7.1
mdurl                              0.1.2
mujoco                             2.3.3
numba                              0.56.4
numpy                              1.23.5
nvidia-cublas-cu12                 12.1.0.26
nvidia-cuda-runtime-cu12           12.1.55
nvidia-cudnn-cu12                  8.9.0.131
oauthlib                           3.2.2
opencv-python                      4.7.0.72
opensimplex                        0.4.4
opt-einsum                         3.3.0
packaging                          23.0
paramiko                           3.1.0
Pillow                             9.5.0
pip                                22.0.2
protobuf                           3.19.6
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycparser                          2.21
Pygments                           2.14.0
PyNaCl                             1.5.0
PyOpenGL                           3.1.6
pyparsing                          3.0.9
python-dateutil                    2.8.2
reprint                            0.6.0
requests                           2.28.2
requests-oauthlib                  1.3.1
rich                               13.3.3
rsa                                4.9
ruamel.yaml                        0.17.21
ruamel.yaml.clib                   0.2.7
scipy                              1.10.1
setuptools                         59.6.0
six                                1.16.0
tabulate                           0.9.0
tensorboard                        2.8.0
tensorboard-data-server            0.6.1
tensorboard-plugin-wit             1.8.1
tensorflow                         2.8.3
tensorflow-estimator               2.8.0
tensorflow-io-gcs-filesystem       0.32.0
tensorflow-probability             0.16.0
tensorrt                           8.6.0
termcolor                          2.2.0
tqdm                               4.65.0
typing_extensions                  4.5.0
urllib3                            1.26.15
Werkzeug                           2.2.3
wheel                              0.37.1
wrapt                              1.15.0
```

**Comment by jdubkim** [comment]
@danijar Just a quick follow-up on this issue. Whenever you get a chance, any updates or suggestions would be awesome. Appreciate your work on this project!

**Comment by danijar** [comment]
What's your GPU?

Could you post a screenshot of the"timer.*avg" and "timer.*frac" scalar metrics from TensorBoard/WandB?

You can use `--jax.prealloc False` if you don't want to allocate all memory upfront, at a small performance cost.

**Comment by jdubkim** [comment]
Hey Danijar,

Thanks a lot for getting back to me!
I'm using a GPU cluster at our university, so my options are Tesla T4 (16GB VRAM, I hear it's around 3-4x slower than V100), an unknown GPU with 24GB VRAM (I'll update this comment once I find its name), and NVIDIA Titan Xp (12GB VRAM).

Here are the TensorBoard results for running [dmc_vision / dmc_walker_walk](https://gist.github.com/jdubkim/63b6ddda09ab74757f21edba908909d8):
<img width="1371" alt="Screenshot 2023-04-29 at 22 11 30" src="https://user-images.githubusercontent.com/18008640/235324379-d3aa1fa1-2229-4d3d-a17e-e65172f12c26.png">
<img width="1379" alt="Screenshot 2023-04-29 at 22 11 45" src="https://user-images.githubusercontent.com/18008640/235324387-f583275d-be97-4c53-8db5-e7a0ca9de06d.png">
<img width="1372" alt="Screenshot 2023-04-29 at 22 11 57" src="https://user-images.githubusercontent.com/18008640/235324395-cbde134b-b676-4a82-80e1-169a7ddc628d.png">

I also tried using ```--jax.prealloc False```, but it seems not to work, probably because Director doesn't use Jax and that config is only available for the Dreamer v3 codebase.

Looking forward to your thoughts on this. Thanks again!

**Comment by danijar** [comment]
Okay almost all time is spent during the train step on the GPU, so there isn't really anything to speed it up other than getting a faster GPU.
